### ISSUE TITLE
How do I connect to slpdb from a client? Even slpdb.bitcoin.com?

### ISSUE THREAD

**Issue by projectoblio** [simpleledger/SLPDB#10]
How can I connect to slpdb.bitcoin.com to listen for token transactions? Can we enable a websocket server for this?

Thanks

**Comment by projectoblio** [comment]
Ah sorry. Okay so all I need to do is subscribe here using ZeroMQ:  `https://slpdb.bitcore.com:28339`

Except clients might not be able to connect to this port from e.g. a Starbucks Cafe due to port restrictions

So I will create a reverse proxy at https://something.com which will do this for me

**Comment by projectoblio** [comment]
I am going to proxy these connections over socket.io

Connecting using node-zmq:

```
var zmq = require('zeromq')
  , sock = zmq.socket('sub');

sock.connect('tcp://slpdb.bitcoin.com:28339');

console.log('Subscriber connected to port 28339');
var subscriptions=["mempool-slp-genesis",
		"mempool-slp-mint",
		"mempool-slp-send"];
var blockSubscriptions = [
		"block-slp-genesis",
		"block-slp-mint",
		"block-slp-send"
	]

sock.subscribe("mempool-slp-send");
sock.subscribe("block-slp-send");

sock.on('message', function(topic, message) {
  console.log('received a message related to:', topic, 'containing message:', message);
});
```


Am I doing something wrong? I can't receive any mesages even when I am the one to send it to the mempool

**Comment by jcramer** [comment]
The server slpdb.bitcoin.com most likely does not have zmq ports open for you to connect to.  You have 2 options:

1. Wait a couple weeks for the project `slp-socket`, which will provide a public way for you to get socket notifications
2. Run your own SLPDB instance and connect to the ZMQ ports locally.

**Comment by jcramer** [comment]
I am closing this issue, let me know if you have any questions still.
