### ISSUE TITLE
utxos collection should be able to be searched by txid only

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/SLPDB#16]
If for instance one was to create a SLP splitter, it could be useful to see how many utxos from a prior tx are remaining. This currently has to be done by doing something like:

```
$in: [
'txid:vout1',
'txid:vout2',
'txid:vout3',
...
]

```

I think there are two options possible for this:

* `txid` and `vout` could be added, this keeps backwards compatibility at the expense of extra disk usage and bigger documents. In a future version `utxo` could be deprecated.
* `utxo` could be fulltext indexed, this probably will slow down Mongo processing and makes people use regex to search.

**Comment by jcramer** [comment]
This is incorporated in commit 3d6ce2d20895a7e405e30c48b8bffbb81459cc62
