### ISSUE TITLE
Bitdb2.0: Accessing BCH balances and UTXOs

### ISSUE THREAD

**Issue by projectoblio** [simpleledger/SLPDB#22]
Is it possible to use this library for accessing BCH balances and UTXOs ? 

I thought i read somewhere that SLPDB only syncs data starting at the block where SLP tokens were made. If I just change this number, will I be able to use this lib in websockets with BitDB and bitcoin queries?

I can't get any of unwriter's bitdb 2.0 queries to work but they work on his explorer but not slpdb's

**Comment by jcramer** [comment]
SLPDB only stores SLPDB related UTXOs at the moment. Closing this for now.
