### ISSUE TITLE
qty_valid_token_addresses includes addresses with a balance of 0

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/SLPDB#23]
See title. These items don't appear in addresses set so it doesn't make sense to count them here.

EDIT: Or maybe they do... :/ does it make sense to keep 0 token_balance addresses in set and counted?

**Comment by jcramer** [comment]
fixed:

https://github.com/simpleledger/SLPDB/blame/943362b7c90bff81b5b5d2ae541635a01efafd21/slptokengraph.ts#L556
