### ISSUE TITLE
Send queries to SLPDB example. 

### ISSUE THREAD

**Issue by vikas3v** [simpleledger/SLPDB#29]
Hi Everyone,

I am quite new to blockchain, jq and slpdb. From the documentation, I understand that for a local installation of SLPDB, we can connect to the API endpoint at http://localhost:3000/q. 

However, I do not understand how a query can be sent to the endpoint to get results from this local installation. Right now I have slpdb, slpserve and slpsockserve installed and running on my machine. Can you please let me know how I can send a query of the format, say, 
`{
  "v": 3,
  "q": {
    "db": ["t"],
    "find":
    {
      "$query":
      {
        "tokenDetails.tokenIdHex": "959a6818cba5af8aba391d3f7649f5f6a5ceb6cdcd2c2a3dcb5d2fbfc4b08e98"
      }
    },
    "project": {"tokenDetails": 1, "tokenStats": 1, "_id": 0 },
    "limit": 1000
  }
}`
to the endpoint? 

Please let me know if you need any other information. I apologize for posting this as an issue as I feel this is mostly my ignorance.

**Comment by jcramer** [comment]
Just below the editor there is a URL provided for "API Endpoint".  That JSON object is converted to base64 and added to the URL string (i.e. `https://localhost:3000/q/<base64_of_json_query_here>`).

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/988195/57959824-9d0fc600-78d3-11e9-9a14-13ec3db57416.png">

**Comment by jcramer** [comment]
I'm closing this, if there is any issues please open another issue.
