### ISSUE TITLE
Tx recorded as invalid when it isn't, but it's children are recorded as valid

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/SLPDB#69]
https://slpdb.fountainhead.cash/explorer/ewogICJ2IjogMywKICAicSI6IHsKICAgICJmaW5kIjogewogICAgICAiZ3JhcGhUeG4udHhpZCI6ICI0ZmUzNzFmM2NiYzViMjJmYjBjYzQ3OTA1M2MxYzgyNDEyZjFhYjNkNTVmYTA2MDRjZTAzNjMxYTg1Mjg5YTgxIgogICAgfSwKICAgICJsaW1pdCI6IDEwCiAgfQp9

{
        "slpAmount": "100000",
        "address": "simpleledger:qrs77l23pmclphnsjhd82dhxu2nvqssyluugg0jtn5",
        "vout": 1,
        "bchSatoshis": 546,
        "spendTxid": "5f91233a5efc7b81f100d922b3967c82db27187bce22eb2f8a5df434d37dde77",
        "status": "SPENT_INVALID_SLP",
        "invalidReason": "Output burned in an invalid SLP transaction"
      },

looking up that txid with tx.h shows its not in slpdb confirmed collection either

https://slpdb.fountainhead.cash/explorer/ewogICJ2IjogMywKICAicSI6IHsKICAgICJmaW5kIjogewogICAgICAidHguaCI6ICI1ZjkxMjMzYTVlZmM3YjgxZjEwMGQ5MjJiMzk2N2M4MmRiMjcxODdiY2UyMmViMmY4YTVkZjQzNGQzN2RkZTc3IgogICAgfSwKICAgICJsaW1pdCI6IDEwCiAgfQp9

**Comment by jcramer** [comment]
This issue should be fixed now, please reopen if there's still an issue.
