### ISSUE TITLE
tx missing from c collection, however it is in g

### ISSUE THREAD

**Issue by blockparty-sh** [simpleledger/SLPDB#70]
`369774adc5ae2d2983a927d5bc01954ed0ec38551ca4341ae188bbd3857a2a8e`

slpdb.fountainhead.cash, slpdb.electroncash.de, and slpdb.bitcoin.com all affected

There was a reorg on same block height which I suspect is part of issue:

```
{
    "height": 646548,
    "hash": "00000000000000000259405b79c49d095f77c45f9b5e9c7a1f2afd34e05aa4ba",
    "branchlen": 1,
    "status": "valid-fork"
  },
```

---

Also, `a10e2840537cbc47c7744bb6e30f6fd0ce648602552a0ec9d313ff3de3cbecec` is missing from slpdb.fountainhead.cash - but this is not on a fork block

**Comment by jcramer** [comment]
not able to reproduce in any tests, let's reopen if it happens again.
