### ISSUE TITLE
SLPDB crashes after it received block 664381

### ISSUE THREAD

**Issue by scorpiotzh** [simpleledger/SLPDB#77]
[INFO] cache: getRawTransaction
[INFO] JSON RPC: getRawTransaction d985ba3a9b69d8cfbade14d5397d2010ef054568fb7ef155dd929abc8520acfc
SLPJS Validating: b52ceb446cf7f0a2bb5a3f2765faec390f603cf34e8842cbe7467964fb5da5e3
SLPJS Result: true (b52ceb446cf7f0a2bb5a3f2765faec390f603cf34e8842cbe7467964fb5da5e3)

<--- Last few GCs --->

[18576:0x451c240]  1053761 ms: Scavenge 7134.9 (8214.9) -> 7125.4 (8215.4) MB, 59.0 / 0.0 ms  (average mu = 0.234, current mu = 0.216) allocation failure
[18576:0x451c240]  1053948 ms: Scavenge 7138.5 (8215.6) -> 7129.0 (8216.4) MB, 58.0 / 0.0 ms  (average mu = 0.234, current mu = 0.216) allocation failure
[18576:0x451c240]  1054138 ms: Scavenge 7142.3 (8216.4) -> 7132.8 (8216.9) MB, 58.2 / 0.0 ms  (average mu = 0.234, current mu = 0.216) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1376519]
    1: StubFrame [pc: 0x133a361]
Security context: 0x2bbbd49008a1 <JSObject>
    2: divModAny(aka divModAny) [0x2f03d5eff4f9] [/root/bitcoin_cash/SLPDB/node_modules/big-integer/BigInteger.js:~544] [pc=0x374caae473cb](this=0x2a5d9ec804a9 <undefined>,0x211a5ec948b1 <NativeBigInt map = 0x3bbac719fab1>,8388608)
    3: bitwise(aka bitwise) [0x2f03d5eff659] [/root/bitcoin_cash/SLPDB/node_modules/big-integer/BigI...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x9dab80 node::Abort() [node]
 2: 0x9dbd36 node::OnFatalError(char const*, char const*) [node]
 3: 0xb3b45e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb3b7d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xce6b75  [node]
 6: 0xce7206 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xcf309a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xcf3fa5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xcf69b8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
10: 0xcc43ad v8::internal::Factory::NewBigInt(int, v8::internal::AllocationType) [node]
11: 0xe018e2 v8::internal::BigInt::Remainder(v8::internal::Isolate*, v8::internal::Handle<v8::internal::BigInt>, v8::internal::Handle<v8::internal::BigInt>) [node]
12: 0xfce3c5 v8::internal::Runtime_BigIntBinaryOp(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x1376519  [node]
sh: line 1: 18576 Aborted                 node --max_old_space_size=8192 index run
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! slpdb@1.0.0-beta-rc13 start: `tsc && node --max_old_space_size=8192 index run`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the slpdb@1.0.0-beta-rc13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-07T11_12_02_215Z-debug.log

> slpdb@1.0.0-beta-rc13 start /root/bitcoin_cash/SLPDB
> tsc && node --max_old_space_size=8192 index run

[INFO] JSON RPC: getBlockchainInfo
(node:18670) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
[INFO] No token filters loaded.
[INFO] Testing RPC connection...
[INFO] JSON RPC: getBlockCount
[INFO] RPC is initialized.
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for unknown-8230...
[INFO] Block checkpoint retrieved:  664381 0000000000000000030201cda9d109ca42288a9eaed5000fac0c761db829ed1b
reprocessFrom:  664381
[PERF] Indexing Keys: 0.205ms
[INFO] Starting to processing SLP Data. 2020-12-07T11:12:11.657Z
[INFO] JSON RPC: getBlockCount
[INFO] Synchronizing SLPDB with BCH blockchain data... 2020-12-07T11:12:11.659Z
[INFO] Block checkpoint retrieved:  664381 0000000000000000030201cda9d109ca42288a9eaed5000fac0c761db829ed1b
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for unknown-8230...
Init all tokens
[INFO] Telementry response code: 200
[INFO] Telemetry response from status.slpdb.io: {"message":"Success"}
[INFO] Telementry response code: 200
[INFO] Telemetry response from status.slpdb.io: {"message":"Success"}
[INFO] Block checkpoint retrieved:  664381 0000000000000000030201cda9d109ca42288a9eaed5000fac0c761db829ed1b

anybody has same problem?

**Comment by jcramer** [comment]
This version of SLPDB hasn't been optimized to work with every SLP Token ID for the whole blockchain.  This version also doesn't work very well with NFT children.

If you are interested in an enterprise version of SLPDB please send me a message on Telegram (user @jscramer).
