### ISSUE TITLE
Setting maxRetry amount

### ISSUE THREAD

**Issue by SuperCipher** [simpleledger/SLPDB#84]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/6429197/110419927-d3cc5700-80cc-11eb-84dd-0e9630a87cf6.png">

@jcramer 
In case of Bitcoin Cash node service are not ready yet SLPDB will continuously try to connect to it.
Right now SLPDB hardcode a `maxRetries` amount to 2 lead to the server crash after 2 retries.
https://github.com/simpleledger/SLPDB/blob/7e487d234d20421596fe9f59485594f6050433c9/rpc.ts#L26

My suggested solution is to add an environment variable to make `maxRetries` configurable to a higher number.

Example fix.
https://github.com/ActorForth/SLPDB-src/pull/6/commits/e49770cee5ce0b92b43dafdf4572ed38a2abb935
If you are ok with the sample implementation I can create a PR after.

**Comment by jcramer** [comment]
I'd be fine with a pr that preserves the original default for maxTries.  It looks the mentioned commit updates the default to 100.

**Comment by SuperCipher** [comment]
@jcramer 
Which branch should I create PR to.

**Comment by jcramer** [comment]
master is fine.
